version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    image: haoxing-server
    build:
      context: ../HaoXing-server
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=my_db

  frontend:
    image: haoxing-frontend
    build:
      context: ../HaoXing
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - server

  bms:
    image: haoxing-bms
    build:
      context: ../HaoXing-BMS
    restart: always
    ports:
      - "8081:80"

volumes:
  db_data:
